

function PrivacyPolicy() {
  return (
    <div className='max-w-4xl mt-28 mx-auto p-6 bg-white text-gray-900'>
<div className="container mx-auto p-6">
  <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>
  <p className="text-sm text-gray-500 mb-6">Last updated: September 14, 2024</p>

  <p className="mb-6 text-gray-700">
    This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
  </p>

  <p className="mb-6 text-gray-700">
    We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
  </p>

  <h2 className="text-2xl font-semibold mb-4">Interpretation and Definitions</h2>

  <h3 className="text-xl font-semibold mb-2">Interpretation</h3>
  <p className="mb-6 text-gray-700">
    The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
  </p>

  <h3 className="text-xl font-semibold mb-2">Definitions</h3>
  <p className="mb-4 text-gray-700">For the purposes of this Privacy Policy:</p>

  <ul className="list-disc pl-5 mb-6 space-y-4 text-gray-700">
    <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
    <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
    <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Maileyo, Dehradun.</li>
    <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device, or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
    <li><strong>Country</strong> refers to: Uttarakhand, India.</li>
    <li><strong>Device</strong> means any device that can access the Service, such as a computer, a cellphone, or a digital tablet.</li>
    <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
    <li><strong>Service</strong> refers to the Website.</li>
    <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
    <li><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
    <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
    <li><strong>Website</strong> refers to Maileyo, accessible from <a href="https://maileyo.com/" target="_blank" className="text-blue-500 underline">https://maileyo.com/</a></li>
    <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
  </ul>

  <h2 className="text-2xl font-semibold mb-4">Collecting and Using Your Personal Data</h2>

  <h3 className="text-xl font-semibold mb-2">Types of Data Collected</h3>

  <h4 className="text-lg font-semibold mb-2">Personal Data</h4>
  <p className="mb-4 text-gray-700">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>

  <ul className="list-disc pl-5 mb-6 space-y-2 text-gray-700">
    <li>Email address</li>
    <li>First name and last name</li>
    <li>Phone number</li>
    <li>Usage Data</li>
  </ul>

  <h4 className="text-lg font-semibold mb-2">Usage Data</h4>
  <p className="mb-4 text-gray-700">
    Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g., IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers, and other diagnostic data.
  </p>

  <h4 className="text-lg font-semibold mb-2">Information from Third-Party Social Media Services</h4>
  <p className="mb-4 text-gray-700">The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:</p>

  <ul className="list-disc pl-5 mb-6 space-y-2 text-gray-700">
    <li>Google mail</li>
    <li>Outlook</li>
  </ul>

  <h4 className="text-lg font-semibold mb-2">Tracking Technologies and Cookies</h4>
  <p className="mb-4 text-gray-700">
    We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. The technologies We use may include:
  </p>

  <ul className="list-disc pl-5 mb-6 space-y-4 text-gray-700">
    <li><strong>Cookies or Browser Cookies:</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent.</li>
    <li><strong>Web Beacons:</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons to count users who have visited those pages or opened an email and for other related statistics.</li>
  </ul>

  <p className="text-gray-700 mb-6">For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>
</div>
      
    </div>
  )
}

export default PrivacyPolicy
